/* Black-Iron Reliquary: Three.js canvas runtime. React is only the frame. */
import * as THREE from "three";
import { ARENA, add, applyUpgrade, chooseTarget, clamp, createInitialRun, grantXp, normalize, scale, spawnEnemy, type RunState, type Vec2 } from "./simulation";

export const ARENA_BACKGROUND = "/manus-storage/reliquary-arena-background_258bc23f.png";
export const RELIQUARY_MARK = "/manus-storage/reliquary-mark_14de5717.png";

export type RuntimeSnapshot = { elapsed: number; wave: number; hp: number; maxHp: number; xp: number; xpToNext: number; level: number; kills: number; enemyCount: number; gameOver: boolean; paused: boolean; pendingLevelUp: boolean; cards: RunState["cards"] };
export type GameRuntime = { mount: (canvas: HTMLCanvasElement) => void; dispose: () => void; setInput: (input: Vec2) => void; pause: () => void; resume: () => void; restart: () => void; chooseUpgrade: (id: RunState["cards"][number]["id"]) => void; snapshot: () => RuntimeSnapshot };

type EnemyView = { mesh: THREE.Mesh; ring: THREE.Mesh; label: THREE.Sprite; hp: THREE.Mesh; };
type OrbView = { mesh: THREE.Mesh; glow: THREE.Mesh };

const COLORS = { stone: 0x161315, brass: 0xc38a4f, vermilion: 0xb6423f, bone: 0xe5d4b5, ash: 0x80737b, ink: 0x09080a, ember: 0xf2a35b };
function mat(color: number, roughness = 0.8): THREE.MeshStandardMaterial { return new THREE.MeshStandardMaterial({ color, roughness, metalness: color === COLORS.brass ? 0.72 : 0.05 }); }
function makeSpriteLabel(text: string, color: string): THREE.Sprite { const c = document.createElement("canvas"); c.width = 128; c.height = 32; const ctx = c.getContext("2d")!; ctx.font = "bold 15px Source Sans 3, sans-serif"; ctx.fillStyle = color; ctx.textAlign = "center"; ctx.fillText(text, 64, 21); const texture = new THREE.CanvasTexture(c); const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, transparent: true, depthTest: false })); sprite.scale.set(1.4, 0.35, 1); return sprite; }

export function createGameRuntime(onFrame: (snapshot: RuntimeSnapshot) => void, demo = false): GameRuntime {
  let renderer: THREE.WebGLRenderer | undefined; let scene: THREE.Scene | undefined; let camera: THREE.OrthographicCamera | undefined; let raf = 0; let last = 0; let input: Vec2 = { x: 0, y: 0 }; let run = createInitialRun();
  const enemyViews = new Map<number, EnemyView>(); const orbViews = new Map<number, OrbView>(); const projectileViews = new Map<number, THREE.Mesh>();
  let playerMesh: THREE.Group | undefined; let arenaGroup: THREE.Group | undefined; let attackFlash = 0;

  const snapshot = (): RuntimeSnapshot => ({ elapsed: run.elapsed, wave: run.wave, hp: run.player.hp, maxHp: run.player.maxHp, xp: run.player.xp, xpToNext: run.player.xpToNext, level: run.player.level, kills: run.player.kills, enemyCount: run.enemies.filter(e => e.alive).length, gameOver: run.gameOver, paused: run.paused, pendingLevelUp: run.pendingLevelUp, cards: run.cards });

  const createPlayer = () => { const group = new THREE.Group(); const body = new THREE.Mesh(new THREE.CylinderGeometry(0.42, 0.58, 0.95, 8), mat(COLORS.ink)); body.position.y = 0.5; group.add(body); const cloak = new THREE.Mesh(new THREE.ConeGeometry(0.78, 1.3, 8), mat(0x3b2e31)); cloak.position.y = 0.7; group.add(cloak); const hood = new THREE.Mesh(new THREE.SphereGeometry(0.44, 10, 8), mat(0x0b090b)); hood.scale.y = 0.9; hood.position.y = 1.25; group.add(hood); const face = new THREE.Mesh(new THREE.SphereGeometry(0.2, 8, 6), mat(COLORS.bone)); face.scale.set(0.85, 0.6, 0.35); face.position.set(0, 1.2, 0.34); group.add(face); const mace = new THREE.Mesh(new THREE.CylinderGeometry(0.06, 0.06, 1.35, 6), mat(COLORS.brass)); mace.rotation.z = -0.58; mace.position.set(0.55, 0.75, 0.1); group.add(mace); const sigil = new THREE.Mesh(new THREE.TorusGeometry(0.8, 0.035, 6, 32), new THREE.MeshBasicMaterial({ color: COLORS.vermilion, transparent: true, opacity: 0.3 })); sigil.rotation.x = Math.PI / 2; sigil.position.y = 0.05; group.add(sigil); return group; };

  const createArena = () => { arenaGroup = new THREE.Group(); const floor = new THREE.Mesh(new THREE.PlaneGeometry(ARENA.width, ARENA.height), new THREE.MeshStandardMaterial({ color: COLORS.stone, roughness: 1, map: (() => { const c = document.createElement("canvas"); c.width = 512; c.height = 512; const x = c.getContext("2d")!; x.fillStyle = "#1a1415"; x.fillRect(0, 0, 512, 512); x.strokeStyle = "rgba(195,138,79,.16)"; x.lineWidth = 2; for (let i = 0; i < 9; i++) { const p = 28 + i * 58; x.beginPath(); x.moveTo(p, 0); x.lineTo(p + 24, 512); x.stroke(); x.beginPath(); x.moveTo(0, p); x.lineTo(512, p + 14); x.stroke(); } x.strokeStyle = "rgba(182,66,63,.12)"; x.beginPath(); x.arc(256, 256, 162, 0, Math.PI * 2); x.stroke(); const tex = new THREE.CanvasTexture(c); tex.colorSpace = THREE.SRGBColorSpace; return tex; })() })); floor.rotation.x = -Math.PI / 2; arenaGroup.add(floor); const ring = new THREE.Mesh(new THREE.RingGeometry(5.5, 5.56, 64), new THREE.MeshBasicMaterial({ color: COLORS.brass, transparent: true, opacity: 0.28, side: THREE.DoubleSide })); ring.rotation.x = -Math.PI / 2; ring.position.y = 0.015; arenaGroup.add(ring); for (let i = 0; i < 18; i++) { const stone = new THREE.Mesh(new THREE.BoxGeometry(0.35 + (i % 3) * 0.2, 0.25 + (i % 4) * 0.08, 0.35), mat(i % 2 ? 0x272125 : 0x372c2c)); const a = i * 2.7; stone.position.set(Math.cos(a) * (7.8 + (i % 3)), 0.18, Math.sin(a) * (5.2 + (i % 2))); stone.rotation.y = a; arenaGroup.add(stone); } scene!.add(arenaGroup); };

  const createEnemyView = (enemy: RunState["enemies"][number]) => { const color = enemy.kind === "graveborn" ? COLORS.ash : enemy.kind === "bone-hound" ? COLORS.bone : COLORS.vermilion; const mesh = new THREE.Mesh(enemy.kind === "bell-revenant" ? new THREE.CylinderGeometry(0.7, 0.85, 1.4, 8) : enemy.kind === "bone-hound" ? new THREE.OctahedronGeometry(0.5, 0) : new THREE.CapsuleGeometry(0.38, 0.55, 4, 8), mat(color)); mesh.position.set(enemy.position.x, enemy.kind === "bell-revenant" ? 0.8 : 0.45, enemy.position.y); const ring = new THREE.Mesh(new THREE.RingGeometry(enemy.radius * 1.05, enemy.radius * 1.15, 20), new THREE.MeshBasicMaterial({ color: COLORS.vermilion, transparent: true, opacity: 0.65, side: THREE.DoubleSide })); ring.rotation.x = -Math.PI / 2; ring.position.y = 0.03; mesh.add(ring); const label = makeSpriteLabel(enemy.kind === "bell-revenant" ? "BELL" : enemy.kind === "bone-hound" ? "HOUND" : "GRAVE", "#e5d4b5"); label.position.y = 1.5; mesh.add(label); const hp = new THREE.Mesh(new THREE.BoxGeometry(0.9, 0.06, 0.04), new THREE.MeshBasicMaterial({ color: COLORS.vermilion })); hp.position.set(0, 1.3, 0.02); mesh.add(hp); scene!.add(mesh); return { mesh, ring, label, hp }; };

  const syncViews = () => { for (const enemy of run.enemies) { let view = enemyViews.get(enemy.id); if (!view) { view = createEnemyView(enemy); enemyViews.set(enemy.id, view); } view.mesh.visible = enemy.alive; if (enemy.alive) { view.mesh.position.x = enemy.position.x; view.mesh.position.z = enemy.position.y; view.hp.scale.x = clamp(enemy.hp / enemy.maxHp, 0, 1); } } for (const [id, view] of Array.from(enemyViews.entries())) { if (!run.enemies.some(e => e.id === id)) { scene!.remove(view.mesh); enemyViews.delete(id); } } for (const orb of run.orbs) { let view = orbViews.get(orb.id); if (!view) { const mesh = new THREE.Mesh(new THREE.IcosahedronGeometry(0.13, 1), mat(COLORS.ember)); const glow = new THREE.Mesh(new THREE.RingGeometry(0.18, 0.24, 16), new THREE.MeshBasicMaterial({ color: COLORS.ember, transparent: true, opacity: 0.42, side: THREE.DoubleSide })); glow.rotation.x = -Math.PI / 2; mesh.add(glow); scene!.add(mesh); view = { mesh, glow }; orbViews.set(orb.id, view); } view.mesh.visible = orb.alive; view.mesh.position.set(orb.position.x, 0.3, orb.position.y); } };

  const spawn = () => { const enemy = spawnEnemy(run); run.enemies.push(enemy); };
  const step = (dt: number) => { if (!scene || !playerMesh || run.paused || run.gameOver || run.pendingLevelUp) return; const clampedDt = Math.min(dt, 0.04); run.elapsed += clampedDt; run.wave = Math.floor(run.elapsed / 22) + 1; run.spawnTimer -= clampedDt; const spawnInterval = Math.max(0.22, 1.05 - run.elapsed * 0.006); if (run.spawnTimer <= 0) { run.spawnTimer = spawnInterval; spawn(); if (run.wave > 2 && Math.random() < 0.12) spawn(); }
    const movement = demo ? normalize({ x: Math.cos(run.elapsed * 0.35), y: Math.sin(run.elapsed * 0.47) }) : input; run.player.position = { x: clamp(run.player.position.x + movement.x * run.player.moveSpeed * clampedDt, -ARENA.width / 2 + 1, ARENA.width / 2 - 1), y: clamp(run.player.position.y + movement.y * run.player.moveSpeed * clampedDt, -ARENA.height / 2 + 1, ARENA.height / 2 - 1) }; playerMesh.position.set(run.player.position.x, 0, run.player.position.y); playerMesh.rotation.y = Math.atan2(movement.x, movement.y || 1);
    for (const enemy of run.enemies) { if (!enemy.alive) continue; const direction = normalize({ x: run.player.position.x - enemy.position.x, y: run.player.position.y - enemy.position.y }); enemy.position = add(enemy.position, scale(direction, enemy.speed * clampedDt)); enemy.hitTimer = Math.max(0, enemy.hitTimer - clampedDt); const distance = Math.hypot(enemy.position.x - run.player.position.x, enemy.position.y - run.player.position.y); if (distance < enemy.radius + 0.55 && enemy.hitTimer === 0) { run.player.hp -= enemy.damage; enemy.hitTimer = 0.8; if (run.player.hp <= 0) { run.player.hp = 0; run.gameOver = true; } } }
    run.player.attackTimer -= clampedDt; if (run.player.attackTimer <= 0) { const target = chooseTarget(run.player.position, run.enemies); run.player.attackTimer = run.player.attackCooldown; if (target) { const direction = normalize({ x: target.position.x - run.player.position.x, y: target.position.y - run.player.position.y }); const projectile = { id: run.nextProjectileId++, position: { ...run.player.position }, velocity: scale(direction, 11), damage: run.player.attackDamage, life: 1.6, alive: true }; run.projectiles.push(projectile); attackFlash = 0.12; } }
    for (const projectile of run.projectiles) { if (!projectile.alive) continue; projectile.position = add(projectile.position, scale(projectile.velocity, clampedDt)); projectile.life -= clampedDt; if (projectile.life <= 0) projectile.alive = false; for (const enemy of run.enemies) { if (!enemy.alive) continue; const d = Math.hypot(enemy.position.x - projectile.position.x, enemy.position.y - projectile.position.y); if (d < enemy.radius + 0.22) { enemy.hp -= projectile.damage; projectile.alive = false; if (enemy.hp <= 0) { enemy.alive = false; run.player.kills += 1; run.orbs.push({ id: run.nextOrbId++, position: { ...enemy.position }, value: enemy.kind === "bell-revenant" ? 5 : enemy.kind === "bone-hound" ? 2 : 1, alive: true }); } break; } } }
    for (const orb of run.orbs) { if (!orb.alive) continue; const delta = { x: run.player.position.x - orb.position.x, y: run.player.position.y - orb.position.y }; const distance = Math.hypot(delta.x, delta.y); if (distance < run.player.pickupRadius) { orb.position = add(orb.position, scale(normalize(delta), Math.min(10, 4 + (run.player.pickupRadius - distance) * 3) * clampedDt)); } if (distance < 0.55) { orb.alive = false; grantXp(run, orb.value); } }
    run.enemies = run.enemies.filter(e => e.alive || Math.random() < 0.995); run.projectiles = run.projectiles.filter(p => p.alive); run.orbs = run.orbs.filter(o => o.alive); attackFlash = Math.max(0, attackFlash - clampedDt); syncViews(); syncProjectiles(); onFrame(snapshot()); };

  const syncProjectiles = () => { for (const projectile of run.projectiles) { let mesh = projectileViews.get(projectile.id); if (!mesh) { mesh = new THREE.Mesh(new THREE.SphereGeometry(0.12, 8, 6), new THREE.MeshBasicMaterial({ color: COLORS.ember })); scene!.add(mesh); projectileViews.set(projectile.id, mesh); } mesh.position.set(projectile.position.x, 0.55, projectile.position.y); mesh.visible = projectile.alive; } for (const [id, mesh] of Array.from(projectileViews.entries())) if (!run.projectiles.some(p => p.id === id)) { scene!.remove(mesh); projectileViews.delete(id); } };

  const frame = (time: number) => { raf = requestAnimationFrame(frame); const dt = last ? (time - last) / 1000 : 0; last = time; step(dt); if (renderer && scene && camera) renderer.render(scene, camera); };
  const mount = (canvas: HTMLCanvasElement) => { renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); renderer.setSize(window.innerWidth, window.innerHeight); renderer.outputColorSpace = THREE.SRGBColorSpace; scene = new THREE.Scene(); scene.background = new THREE.Color(COLORS.ink); camera = new THREE.OrthographicCamera(-10, 10, 6.2, -6.2, 0.1, 100); camera.position.set(0, 18, 0); camera.lookAt(0, 0, 0); scene.add(new THREE.HemisphereLight(0xd9c5a0, 0x160e14, 1.6)); const key = new THREE.DirectionalLight(0xffc887, 2.5); key.position.set(-4, 12, 4); scene.add(key); createArena(); playerMesh = createPlayer(); scene.add(playerMesh); window.addEventListener("resize", resize); raf = requestAnimationFrame(frame); onFrame(snapshot()); };
  const resize = () => { if (!renderer || !camera) return; const aspect = window.innerWidth / window.innerHeight; const height = 12.4; camera.top = height / 2; camera.bottom = -height / 2; camera.left = -(height * aspect) / 2; camera.right = (height * aspect) / 2; camera.updateProjectionMatrix(); renderer.setSize(window.innerWidth, window.innerHeight); };
  const dispose = () => { cancelAnimationFrame(raf); window.removeEventListener("resize", resize); renderer?.dispose(); scene?.clear(); renderer = undefined; scene = undefined; };
  const restart = () => { run = createInitialRun(); enemyViews.forEach(v => scene?.remove(v.mesh)); enemyViews.clear(); orbViews.forEach(v => scene?.remove(v.mesh)); orbViews.clear(); projectileViews.forEach(v => scene?.remove(v)); projectileViews.clear(); onFrame(snapshot()); };
  return { mount, dispose, setInput: (next) => { input = normalize(next); }, pause: () => { run.paused = true; onFrame(snapshot()); }, resume: () => { if (!run.gameOver && !run.pendingLevelUp) run.paused = false; onFrame(snapshot()); }, restart, chooseUpgrade: (id) => { applyUpgrade(run, id); run.paused = false; onFrame(snapshot()); }, snapshot };
}
